package com.zitto.vcumaster.core

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Checks the Kotlin DBC analyzer + library against the desktop VCU Master (V0.0073):
 * analyzer_ref.json was generated by dbc_engine.py / analyzer.py (cantools 44.1) for every DBC in
 * dbc_library/, library_index.json by library.py.
 */
class AnalyzerTest {
    private val assets = File("src/main/assets")
    private fun res(n: String) = javaClass.classLoader!!.getResource(n)!!.readText()

    private fun close(a: Double, b: Double) = Math.abs(a - b) <= 1e-6 * maxOf(1.0, Math.abs(a), Math.abs(b))

    @Test
    fun analyzerMatchesPythonOnWholeLibrary() {
        val ref = JSONObject(res("analyzer_ref.json"))
        val fails = ArrayList<String>()
        var files = 0
        var roles = 0
        for (rel in ref.keys().asSequence().sorted()) {
            val r = ref.getJSONObject(rel)
            val eng = DbcEngine()
            val text = File(assets, "dbc_library/$rel").readText(Charsets.ISO_8859_1)
            try {
                eng.load(rel.substringAfterLast('/'), text, listOf(1, 2))
            } catch (e: Exception) {
                fails += "$rel: load failed ${e.message}"
                continue
            }
            files++
            val m = eng.rolesMeta()
            val exp = r.getJSONObject("roles")
            val expKeys = exp.keys().asSequence().toList()
            if (expKeys.toSet() != m.roles.keys) {
                fails += "$rel: role keys py-only ${expKeys - m.roles.keys} kt-only ${m.roles.keys - expKeys.toSet()}"
                continue
            }
            for (k in expKeys) {
                val e = exp.getJSONObject(k)
                val a = m.roles.getValue(k)
                roles++
                val diffs = ArrayList<String>()
                if (e.getString("label") != a.label) diffs += "label ${e.getString("label")} / ${a.label}"
                if (e.getString("unit") != a.unit) diffs += "unit ${e.getString("unit")} / ${a.unit}"
                if (e.getString("kind") != a.kind) diffs += "kind ${e.getString("kind")} / ${a.kind}"
                if (e.getString("section") != a.section) diffs += "section"
                if (!close(e.getDouble("min"), a.minimum)) diffs += "min ${e.getDouble("min")} / ${a.minimum}"
                if (!close(e.getDouble("max"), a.maximum)) diffs += "max ${e.getDouble("max")} / ${a.maximum}"
                if (!close(e.getDouble("step"), a.step)) diffs += "step ${e.getDouble("step")} / ${a.step}"
                if (e.getBoolean("derived") != a.derived) diffs += "derived"
                val eb = e.getJSONArray("bindings")
                if (eb.length() != a.bindings.size) diffs += "bindings ${eb.length()} / ${a.bindings.size}"
                else for (i in 0 until eb.length()) {
                    val x = eb.getJSONArray(i)
                    val b = a.bindings[i]
                    if (x.getString(0) != b.msg || x.getString(1) != b.sig || !close(x.getDouble(2), b.factor) || !close(x.getDouble(3), b.offset)) {
                        diffs += "binding $i $x / ${b.msg}.${b.sig} ${b.factor} ${b.offset}"
                    }
                }
                val ec = e.getJSONObject("choices")
                val ac = a.choices ?: emptyMap()
                if (ec.length() != ac.size || ec.keys().asSequence().any { ac[it.toLong()] != ec.getString(it) }) diffs += "choices"
                if (diffs.isNotEmpty()) fails += "$rel $k: $diffs"
            }
            fun strs(n: String) = r.getJSONArray(n).let { j -> (0 until j.length()).map { j.getString(it) } }
            if (strs("cells") != m.cells) fails += "$rel: cells"
            if (strs("temps") != m.temps) fails += "$rel: temps"
            if (strs("panels") != m.panels) fails += "$rel: panels ${strs("panels")} / ${m.panels}"
            val bal = r.getJSONObject("balance")
            if (bal.length() != m.balance.size || bal.keys().asSequence().any { m.balance[it.toInt()] != bal.getString(it) }) fails += "$rel: balance"
            val fl = r.getJSONObject("flags")
            for (p in fl.keys()) {
                val ef = fl.getJSONArray(p).let { j -> (0 until j.length()).map { j.getJSONArray(it).let { x -> "${x.getString(0)}.${x.getString(1)}:${x.getString(2)}" } } }
                val af = m.flags[p].orEmpty().map { "${it.msg}.${it.sig}:${it.kind}" }
                if (ef != af) fails += "$rel: flags $p (${ef.size} / ${af.size}) ${ef.minus(af.toSet()).take(3)} ${af.minus(ef.toSet()).take(3)}"
            }
        }
        println("analyzer: $files files, $roles roles compared, ${fails.size} differences")
        fails.take(60).forEach { println(it) }
        assertTrue("${fails.size} differences, first: ${fails.firstOrNull()}", fails.isEmpty())
    }

    @Test
    fun libraryIndexMatchesParser() {
        val lib = DbcLibrary(File(assets, "library_index.json").readText())
        assertEquals(189, lib.items.size)
        val fails = ArrayList<String>()
        for (i in lib.items) {
            if (i.ids.isEmpty()) continue           // cantools could not read it either
            val db = DbcParser.parse(File(assets, "dbc_library/${i.id}").readText(Charsets.ISO_8859_1))
            val ids = db.messages.map { it.frameId to it.ext }.toSet()
            if (ids != i.ids) fails += "${i.id}: ${ids.size} / ${i.ids.size}"
        }
        fails.forEach { println(it) }
        assertTrue(fails.toString(), fails.isEmpty())
    }

    @Test
    fun libraryMatchFindsDaly() {
        val lib = DbcLibrary(File(assets, "library_index.json").readText())
        val seen = setOf(0x18904001L to true, 0x18914001L to true, 0x18924001L to true, 0x18934001L to true)
        val best = lib.match(seen).first()
        assertTrue(best.id, best.id.startsWith("BMS/Daly/"))
        assertEquals(4, best.matched)
    }

    @Test
    fun dalyBatteryRolesDecode() {
        val eng = DbcEngine()
        eng.load("daly.dbc", File(assets, "dbc_library/BMS/Daly/Daly_BMS_CAN_V1.0_from_spec.dbc").readText(Charsets.ISO_8859_1), listOf(2))
        val meta = eng.rolesMeta()
        assertEquals(48, meta.cells.size)
        assertTrue("bms.cell_count" in meta.roles)
        // SOC 87.5 %, current 12.3 A (offset -3000), voltage 52.1 V (Motorola 16 bit fields)
        fun be(v: Int) = listOf((v shr 8) and 0xFF, v and 0xFF)
        val data = be(521) + be(521) + be(30123) + be(875)
        eng.decode(2, 0x18904001L, true, data, 1.0)
        assertEquals(87.5, eng.roleValues.getValue("bms.soc"), 1e-9)
        assertEquals(12.3, eng.roleValues.getValue("bms.current"), 1e-9)
        assertTrue(eng.unknownIds(1.0).isEmpty())
        eng.decode(2, 0x123L, false, listOf(1, 2), 1.0)
        assertEquals(setOf(0x123L to false), eng.unknownIds(1.0).keys)
    }
}
